Standardize scripts

diff --git a/hook-scripts/post-applypatch b/hook-scripts/post-applypatch
--- a/hook-scripts/post-applypatch
+++ b/hook-scripts/post-applypatch
@@ -1,13 +1,15 @@
 #!/bin/sh
 
-mypath="`echo $0 | sed -e 's,[^/]*$,,;s,/$,,;s,^$,.,'`"
-cd ${mypath}
-mypath=$PWD
+debug() { ! "${log_debug-false}" || log "DEBUG: $*" >&2; }
+log() { printf '%s\n' "$*"; }
+warn() { log "WARNING: $*" >&2; }
+error() { log "ERROR: $*" >&2; }
+fatal() { error "$*"; exit 1; }
 
-${mypath}/../../hook-scripts/update-setup
-if [ -e "${HOME}/.gitconfig" ]; then
-  ${mypath}/../../hook-scripts/setup-gitconfig "${HOME}/.gitconfig"
-fi
+mydir=$(cd "$(dirname "$0")" && pwd -L) || fatal "Unable to determine script directory"
+
+${mydir}/../../hook-scripts/update-setup || error "updating setup"
+${mydir}/../../hook-scripts/setup-gitconfig || error "updating git config"
 
 
 
