Switch to shell script for git config setup
Don't need configdict anymore as I'm just calling "git config"

diff --git a/hook-scripts/setup-gitconfig b/hook-scripts/setup-gitconfig
--- a/hook-scripts/setup-gitconfig
+++ b/hook-scripts/setup-gitconfig
@@ -1,49 +1,32 @@
-#!/usr/bin/env python
+#!/bin/sh
 
-import ConfigParser
-import sys
-import os
+debug() { ! "${log_debug-false}" || log "DEBUG: $*" >&2; }
+log() { printf '%s\n' "$*"; }
+warn() { log "WARNING: $*" >&2; }
+error() { log "ERROR: $*" >&2; }
+fatal() { error "$*"; exit 1; }
 
-mypath = os.path.dirname(sys.argv[0])
-sys.path.append(os.path.join(mypath, "../lib/configdict"))
-import configdict
+mydir=$(cd "$(dirname "$0")" && pwd -L) || fatal "Unable to determine script directory"
 
-def writeConfig(config, output):
-    output.write(config.tostring())
+case "${USER}" in
+    'jschewe')
+        git config --global user.email 'jschewe@bbn.com'
+        ;;
+    'jpschewe')
+        git config --global user.email 'jpschewe@mtu.net'
+        ;;
+esac
 
-def determineEmail():
-    username = os.environ['USER']
-    if username:
-        if username == 'jschewe':
-            return 'jschewe@bbn.com'
-        else:
-            return 'jpschewe@mtu.net'
-    else:
-        return None
+# push nothing, always use explicit
+git config --global push.default nothing
 
-if __name__ == "__main__":
-    config = ConfigParser.RawConfigParser()
-    config = configdict.ConfigDict(sys.argv[1])
-    email = determineEmail()
-    if email:
-        config['user']['email'] = email
+# turn on colors
+git config --global color.branch 'auto'
+git config --global color.diff 'auto'
+git config --global color.status 'auto'
+git config --global color.ui 'auto'
 
-    config['user']['name'] = 'Jon Schewe'
-
-    # push nothing, always use explicit
-    config['push']['default'] = 'nothing'
-
-    # turn on colors
-    config['color']['branch'] = 'auto'
-    config['color']['diff'] = 'auto'
-    config['color']['status'] = 'auto'
-    config['color']['ui'] = 'auto'
-
-    # aliases
-    config['alias']['nlog'] = 'log --date=relative --abbrev-commit --graph'
-    config['alias']['redocommit'] = 'reset --soft HEAD^'
-    config['alias']['diffemptytreehash'] = 'diff -p 4b825dc642cb6eb9a060e54bf8d69288fbee4904'
-
-    output = file(sys.argv[1], "w")
-    writeConfig(config, output)
-    output.close()
+# aliases
+git config --global alias.nlog 'log --date=relative --abbrev-commit --graph'
+git config --global alias.redocommit 'reset --soft HEAD^'
+git config --global alias.diffemptytreehash 'diff -p 4b825dc642cb6eb9a060e54bf8d69288fbee4904'
